Read default proto version from `third_party_release`
open-telemetry/opentelemetry-cpp pull request #2677
Opened 2024-05-23 03:04 UTC by owent

Fixes #2676 
## Changes

+ Read default proto version from `third_party_release`

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

2024-05-23 06:58 UTC, marcalff commented on cmake/opentelemetry-proto.cmake
> +        set(opentelemetry-proto "v1.1.0")
```suggestion
        set(opentelemetry-proto "v1.3.1")
```

2024-05-23 07:01 UTC, marcalff approved these changes
Thanks for the fix.

See suggested change.

Not sure why opentelemetry-proto.cmake was not formatted in my previous change, as CI was ok on format.

2024-05-23 07:06 UTC, marcalff requested changes
Also, please update third_party_release to use opentelemetry-proto 1.3.1

(Edit: this is something missing from PR #2669)

2024-05-28 04:35 UTC, owent commented on cmake/opentelemetry-proto.cmake
> +        set(opentelemetry-proto "v1.1.0")
Done

2024-05-28 04:37 UTC, owent commented
> Thanks for the fix.
> 
> See suggested change.
> 
> Not sure why opentelemetry-proto.cmake was not formatted in my previous change, as CI was ok on format.

Maybe we should use `cmake-format -i $($FIND -name 'CMakeLists.txt' -print -o -name '*.cmake' -print -o -name '*.cmake.in' -print)` in `tools/format.sh`. (Add `-o` between rules.)

2024-05-28 07:06 UTC, marcalff approved these changes
LGTM, thanks for the fix.

2024-05-28 09:04 UTC, merged