potential fix for std::variant implicit conversion in C++17 STL
open-telemetry/opentelemetry-cpp pull request #734
Opened 2021-05-10 15:53 UTC by lalitb

Fixes ##733

## Changes

@maxgolov  This is not for merge, but to showcase the potential changes needed to fix #733, As mentioned in the comment there, this is not related to resource sdk.

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

2021-05-10 18:15 UTC, lalitb commented
> I'm Okay with this as a temporary measure. I think we could have handled it in the `AttributeValue` class.

This is not related to `string_view`. As an example, resource sdk doesn't use `AttributeValue`, but directly uses `OwnedAttributeValue`. The problem is with the implicit conversion of `char *` to `bool` in C++17, which seems to be corrected in C++20. Please see my comment on the issue you created.

2021-05-10 18:46 UTC, ThomsonTan commented on exporters/ostream/test/ostream_log_test.cc
> +  record->SetResource("key1", std::string("val1"));
Could we provide an explicit overload to `SetResource` with `const char *` to avoid potential future error?

2021-05-20 06:41 UTC, maxgolov requested changes
I don't like that. I'm proposing to re-add `const char *` to variant. Just verified that it works, and including it in the Abseil Variant PR.

This re-add of `const char *` will give us much nicer user / developer experience, when we get to C++17 standard lib impl of variant.

2021-05-26 09:04 UTC, lalitb commented
> I don't like that. I'm proposing to re-add `const char *` to variant. Just verified that it works, and including it in the Abseil Variant PR.
> 
> This re-add of `const char *` will give us much nicer user / developer experience, when we get to C++17 standard lib impl of variant.

Agree, it's not fully user-friendly, but it keeps api/sdk stable. Unless we plan to add `const char *` to `OwnedAttributeValue`, these changes need to go through.

2021-05-26 12:26 UTC, closed without merging