add documentation for GRPC Env variables
open-telemetry/opentelemetry-cpp pull request #974
Opened 2021-09-08 21:31 UTC by lalitb

Fixes #971 

## Changes

This PR adds documentation for the configuration option ( through struct and env-var ) used for `otlp-grpc` and `otlp-http` exporter. Also document that the env variable name are not same as defined in spec.

For significant contributions please make sure you have completed the following items:

* [ ] `CHANGELOG.md` updated for non-trivial changes
* [ ] Unit tests have been added
* [ ] Changes in public API reviewed

2021-09-08 21:39 UTC, ThomsonTan commented on exporters/otlp/README.md
> +Note: These env variables names are not same as in [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.0/specification/protocol/exporter.md).
```suggestion
Note: These environment variable names are not same as in [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.0/specification/protocol/exporter.md).
```

2021-09-08 21:48 UTC, ThomsonTan commented on exporters/otlp/README.md
> +| `timeout`  | n/a  | `3000 ms` | http timeout |
```suggestion
| `timeout`  | n/a  | `30000 ms` | http timeout |
```
https://github.com/open-telemetry/opentelemetry-cpp/blob/main/exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_exporter.h#L70

2021-09-08 22:14 UTC, lalitb commented on exporters/otlp/README.md
> +| `timeout`  | n/a  | `3000 ms` | http timeout |
good catch :)

2021-09-09 17:01 UTC, jsuereth requested changes
Commented on the bug as well.

I don't think this is sufficient for a 1.0 against the specification.

I think there are two enviornment variables here that you can leave for legacy users BUT you should provide the new environment variables as alternatives, specifically:

`OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` and `OTEL_EXPORTER_OTLP_TRACES_CERTIFICATE`

2021-09-09 22:18 UTC, lalitb commented
@jsuereth  - It was creating more noise in code to support both legacy and compliant environment variables, and would further increase in future once we start supporting `OTEL_EXPORTER_OTLP_[TRACES_]PROTOCOL`. Keeping that in mind, have removed legacy environment variables. This would be breaking change ( hopefully won't affect lots of users ), and we will document this in release description.

2021-09-09 22:19 UTC, lalitb commented on exporters/otlp/src/otlp_grpc_exporter.cc
> +
will remove this file later.

2021-09-13 22:08 UTC, lalitb commented
@owent - As this env variables were initially modified by you, would like to have a look into this PR. Thanks.

2021-09-14 02:04 UTC, owent commented
> @owent - As these env variables were initially modified by you, would like to have a look into this PR. Thanks.

LGTM.

Should we also make the same changes for `OtlpHttpExporter` ?

2021-09-14 03:30 UTC, lalitb commented
> LGTM.
> 
> Should we also make the same changes for `OtlpHttpExporter` ?                     

Thanks for reviewing @owais. `OtlpHttpExporter` doesn't support environment variables yet, so we are not non-compliant there :) Will create a github issue for adding env variables there.

2021-09-14 05:27 UTC, owent commented
> > LGTM.
> > Should we also make the same changes for `OtlpHttpExporter` ?
> 
> Thanks for reviewing @owais. `OtlpHttpExporter` doesn't support environment variables yet, so we are not non-compliant there :) Will create a github issue for adding env variables there.

OK. I think I can add support of these environment variables for `OtlpHttpExporter` then:

+ `OTEL_EXPORTER_OTLP_ENDPOINT`
+ `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT`
+ `OTEL_EXPORTER_OTLP_HEADERS`
+ `OTEL_EXPORTER_OTLP_TRACES_HEADERS`

But `OTEL_EXPORTER_OTLP_CERTIFICATE` and `OTEL_EXPORTER_OTLP_TRACES_CERTIFICATE` can be available only after #938 is finished.

2021-09-14 05:59 UTC, lalitb commented
> OK. I think I can add support of these environment variables for `OtlpHttpExporter` then:
> 
> * `OTEL_EXPORTER_OTLP_ENDPOINT`
> * `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT`
> * `OTEL_EXPORTER_OTLP_HEADERS`
> * `OTEL_EXPORTER_OTLP_TRACES_HEADERS`
> * `OTEL_EXPORTER_OTLP_TIMEOUT`
> * `OTEL_EXPORTER_OTLP_TRACES_TIMEOUT`

That would be awesome :)

> But OTEL_EXPORTER_OTLP_CERTIFICATE and OTEL_EXPORTER_OTLP_TRACES_CERTIFICATE can be available only after #938 is finished.

Agree.

2021-09-14 17:55 UTC, jsuereth approved these changes

2021-09-14 21:28 UTC, merged